version: "3.1"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cric11-backend-image
    container_name: cric11-backend-container
    ports:      
      - "4000:8000"
    env_file:
      - .env

    volumes: 
      - .:/usr/src/cric11-backend
    depends_on:
      - redis

  # redis:
  #   image: redis:7
  #   container_name: redis-server
  #   ports:
  #     - "6379:6379" 
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

    